### ISSUE TITLE
sendTags only sends one tag?

### ISSUE THREAD

**Issue by avishayil** [one-signal/OneSignal-iOS-SDK#12] opened 2016-02-21 14:50 UTC
I'm calling `[oneSignal sendTags:properties]` while `properties` equals:
`properties	__NSCFDictionary *	20 key/value pairs	0x17fb7ce0`
and contains 20 key value strings.

After this runs it returns `success` but I can only see one tag on the OneSignal user page.

**Comment by jkasten2** [comment] 2016-02-23 19:42
@avishayil I was not able to reproduce the issue with a dictionary with 20 key value pairs. Could you `NSLog` the contains of `properties`?

**Comment by jkasten2** [comment] 2016-02-27 02:03
@avishayil Do have any nested arrays or non-string types in your `NSDictionary`?

**Comment by jkasten2** [comment] 2016-06-03 03:10
@avishayil Closing this issue. Feel free to open the issue if you are able to reproduce it.

**Closed by jkasten2** 2016-06-03 03:10 UTC
